site_name: Programació web en Entorn Servidor 2026
site_url: https://cipfpbatoi.github.io/dwes2627/
use_directory_urls: false

nav:
  - "Inici": "index.md"
  - "Com funciona el curs": "01_com_funciona_el_curs/index.md"
  - "Reptes":
      - "Visió general": "02_reptes/index.md"
      - "Repte 01": "02_reptes/repte_01.md"
      - "Repte 02": "02_reptes/repte_02.md"
      - "Repte 03": "02_reptes/repte_03.md"
      - "Repte 04": "02_reptes/repte_04.md"
      - "Repte 05": "02_reptes/repte_05.md"
      - "Fase final": "02_reptes/fase_final.md"
  - "Com s'avalua":
      - "Visió general": "03_com_s_avalua/index.md"
      - "Evidències": "03_com_s_avalua/evidencies.md"
      - "Checkpoints i defenses": "03_com_s_avalua/checkpoints_i_defenses.md"
  - "Materials": "04_materials/index.md"
  - "Projecte base": "05_projecte_base/index.md"
  - "Recursos ràpids": "06_recursos_rapid/index.md"
theme:
  language: ca
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: default
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Canviar a mode nit
    - scheme: slate 
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Canviar a mode dia
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - content.tabs.link
    # - navigation.tabs
    # - navigation.top

extra:
  search:
    language: "ca"
  social:
    - icon: material/email-edit
      link: mailto:<i.gomismullor@edu.gva.es>
  analytics:
    provider: google
    property: G-X6D0LR7TC8

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2026-2027 Ignasi Gomis  - Licencia CC BY-NC-SA
